### ISSUE TITLE
Error module import

### ISSUE THREAD

**Issue by LORDTEK** [harvitronix/reinforcement-learning-car#12]
:~/reinforcement-learning-car$ python3 learning.py
Loading chipmunk for Linux (64bit) [/usr/local/lib/python3.5/dist-packages/pymunk/libchipmunk64.so]
Using TensorFlow backend.
Traceback (most recent call last):
  File "learning.py", line 5, in <module>
    from nn import neural_net, LossHistory
  File "/home/archer/reinforcement-learning-car/nn.py", line 6, in <module>
    from keras.models import Sequential
  File "/home/archer/.local/lib/python3.5/site-packages/keras/__init__.py", line 3, in <module>
    from . import activations
  File "/home/archer/.local/lib/python3.5/site-packages/keras/activations.py", line 4, in <module>
    from . import backend as K
  File "/home/archer/.local/lib/python3.5/site-packages/keras/backend/__init__.py", line 73, in <module>
    from .tensorflow_backend import *
  File "/home/archer/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
ImportError: No module named 'tensorflow'

**Comment by Microos** [comment]
keras use tensorflow as its backend and you may need to get that installed.
